### ISSUE TITLE
organizationにしてもよい？

### ISSUE THREAD

**Issue by reizist** [5704k3/piyopiyorb#2]
気軽なきもちでissue立ててるので気軽なきもちでレス/closeして頂ければと思います＞＜

せっかくなのでpiyopiyorbのorganization作っても良いのではなどと思いました(╹◡╹)

**Comment by 5470x3** [comment]
おー、ありがとうございます。(´ー`)
Organizationって別プランになるんでしたっけ。Contributorが増えたら考えようかなと思ってはいますが…

**Comment by reizist** [comment]
https://github.com/account/organizations/new

privateレポジトリはもちろん有料ですが、オープンであれば基本的に無料です〜！
確かにまだまだ人の集まり状況とかわからないですもんね＞＜　すみません！
